package(default_visibility=["//visibility:public"])

cc_library(
  name = "cpor",
  srcs = ["cpor.pb.cc"],
  hdrs = ["cpor.pb.h"],
  deps = [],
  copts = [
    "-I/usr/local/include",
    "-D_THREAD_SAFE",
    "-L/usr/local/lib",
    "-lprotobuf",
    "-D_THREAD_SAFE",
  ],
)
