package(default_visibility=["//visibility:public"])

cc_library(
  name = "cpor",
  srcs = ["cpor.pb.cc"],
  hdrs = ["cpor.pb.h"],
  deps = [],
  linkopts = [
    "-L/usr/local/lib",
    "-lprotobuf",
  ],
  copts = [
    "-I/usr/local/include",
  ],
)
