cc_library(
    name = "file_browser",
    hdrs = ["file_browser.h"],
    srcs = ["file_browser.cc"],
    deps = [
        ":file_list_source",
    ]
)

cc_library(
    name = "file_list_source",
    hdrs = ["file_list_source.h"]
)

